
version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
    volumes:
      - ${JELLYFIN_DATABASE_LOC}:/config
      - ${STORAGE}:/Storage
      - ${TVSHOWS_LOC}:/data/tvshows
      - ${MOVIES_LOC}:/data/movies

    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - homeServerNetwork
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${CUSTOM_TIME_ZONE}
    #ports:
    #  - ${JELLYSEERR_PORT}:5055
    volumes:
      - ${JELLYSEERR_DATABASE_LOC}:/app/config
    networks:
      - homeServerNetwork
    restart: unless-stopped    
  ########################################
  #  Trying out Jellyfin and jeelyseerr  #
  ########################################
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    networks:
      - homeServerNetwork
    ports:
      - ${PLEX_MEDIA_SERVER_PORT}:32400/tcp
    #  - ${PLEX_COMPANION_PORT}:3005/tcp
    #  - ${PLEX_FOR_ROKU_PORT}:8324/tcp
    #  - ${PLEX_DLNA_SERVER_ACCESS_PORT}:32469/tcp
    #  - ${PLEX_DLNA_SERVER_PORT}:1900/udp
    #  - ${GDM_NETWORK_PORT1}:32410/udp
    #  - ${GDM_NETWORK_PORT2}:32412/udp
    #  - ${GDM_NETWORK_PORT3}:32413/udp
    #  - ${GDM_NETWORK_PORT4}:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=${CUSTOM_TIME_ZONE}
      - FILE__PLEX_CLAIM=./plex_claim
      - ADVERTISE_IP=${PLEX_HOST_SCHEME}${PLEX_HOST_IP}:${PLEX_MEDIA_SERVER_PORT}/
    hostname: plex
    volumes:
      - ${PLEX_DATABASE_LOC}:/config
      - ${STORAGE}:/Storage
      #- ${TVSHOWS_LOC}:/tv
      #- ${MOVIES_LOC}:/movies
      #- ${PLEX_TRANSCODE_LOC}:/transcode
      #- ${PLEX_MEDIA_LOC}:/data
      #- ${EXTERNAL_MEDIA}:/external_media
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
    volumes:
      - ${OVERSEERR_CONFIG}:/config
      - ${DOWNLOADS_LOC}:/data
    #ports:
    #  - ${OVERSEERR_PORT}:5055
    networks:
      - homeServerNetwork
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
    volumes:
      - ${PROWLARR_CONFIG}:/config
    #ports:
    #  - ${PROWLARR_PORT}:9696
    networks:
      - homeServerNetwork
    restart: unless-stopped
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
      - fpm=${ORGANIZR_FPM}
      - branch=${ORGANIZR_MAIN_BRANCH}
    volumes:
      - ${ORGANIZR_CONFIG}:/config
    #ports:
    #  - ${ORGANIZR_PORT}:80
    networks:
      - homeServerNetwork
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${MOVIES_LOC}:/data
      - ${STORAGE}:/Storage
      #- ${MOVIES_LOC}:/movies #optional
      #- ${DOWNLOADS_LOC}:/downloads #optional
      #- ${EXTERNAL_MEDIA}:/external_media
    #ports:
    #  - ${RADARR_ACCESS_PORT}:7878
    networks:
      - homeServerNetwork
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
    volumes:
      - ${SONARR_CONFIG_PATH}:/config
      - ${TVSHOWS_LOC}:/data
      - ${STORAGE}:/Storage
      #- ${TVSHOWS_LOC}:/tv #optional
      #- ${DOWNLOADS_LOC}:/downloads #optional
      #- ${EXTERNAL_MEDIA}:/external_media
    #ports:
    #  - ${SONARR_ACCESS_PORT}:8989
    networks:
      - homeServerNetwork
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
    volumes:
      - ${BAZARR_CONFIG_PATH}:/config
      - ${STORAGE}:/Storage
      #- ${MOVIES_LOC}:/movies #optional
      #- ${TVSHOWS_LOC}:/tv #optional
    #ports:
    #  - ${RADARR_ACCESS_PORT}:6767
    networks:
      - homeServerNetwork
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
      - WEBUI_PORT=${QBITTORRENT_PORT}
    volumes:
      - ${QBITTORRENT_CONFIG}:/config
      - ${STORAGE}:/Storage
      #- ${DOWNLOADS_LOC}:/downloads
    ports:
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}
      - 6881:6881
      - 6881:6881/udp
    networks:
      - homeServerNetwork
    restart: unless-stopped
  #filebot:
  #  image: ghostserverd/filebot:4.9.x
  #  container_name: filebot
  #  restart: unless-stopped
  #   ports:
  #    - "7070:7070"
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - SHARE_BASE_PATH=/server
  #    - OPEN_SUB_USER=someuser
  #    - OPEN_SUB_PASS=somepass
  #    - TZ=${CUSTOM_TIME_ZONE}
  #  volumes:
  #    - ${FILEBOT_CONFIG}:/config
  #    - ${DOWNLOADS_LOC}:/downloads
  #    - /server/media:/server/media
  #  networks:
  #    - homeServerNetwork
  tautulli:
    image: ghostserverd/tautulli
    container_name: tautulli
    restart: unless-stopped
    #ports:
    #  - "${TAUTULLI_PORT}:8181"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
    volumes:
      - ${TAUTULLI_CONFIG}:/config
      - "${PLEX_DATABASE_LOC}/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    networks:
      - homeServerNetwork
  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped
    hostname: ${NETDATA_HOSTNAME}
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/os-release:/host/etc/os-release:ro
    networks:
      - homeServerNetwork
  apache-proxy:
    build: ./apache
    container_name: apache-proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${CUSTOM_TIME_ZONE}
    volumes:
      - ./apache/vhosts/:/usr/local/apache2/conf/sites/
      - ./data/apache_logs/:/usr/local/apache2/logs/
    networks:
      - homeServerNetwork
    ports:
      - ${APACHE_PORT}:80
    restart: unless-stopped

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  homeServerNetwork:
    driver: bridge
